export const abiP256 = [
   {
      "inputs":[
         {
            "internalType":"bytes",
            "name":"challenge",
            "type":"bytes"
         },
         {
            "internalType":"bool",
            "name":"requireUserVerification",
            "type":"bool"
         },
         {
            "internalType":"bytes",
            "name":"encodedAuth",
            "type":"bytes"
         },
         {
            "internalType":"bytes32",
            "name":"x",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"y",
            "type":"bytes32"
         }
      ],
      "name":"verifyCompactSignature",
      "outputs":[
         {
            "internalType":"bool",
            "name":"isValid",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes",
            "name":"challenge",
            "type":"bytes"
         },
         {
            "internalType":"bool",
            "name":"requireUserVerification",
            "type":"bool"
         },
         {
            "internalType":"bytes",
            "name":"encodedAuth",
            "type":"bytes"
         },
         {
            "internalType":"bytes32",
            "name":"x",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"y",
            "type":"bytes32"
         }
      ],
      "name":"verifyEncodedSignature",
      "outputs":[
         {
            "internalType":"bool",
            "name":"isValid",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"hash",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"r",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"s",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"x",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"y",
            "type":"bytes32"
         }
      ],
      "name":"verifyP256Signature",
      "outputs":[
         {
            "internalType":"bool",
            "name":"isValid",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes32",
            "name":"hash",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"r",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"s",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"x",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"y",
            "type":"bytes32"
         }
      ],
      "name":"verifyP256SignatureAllowMalleability",
      "outputs":[
         {
            "internalType":"bool",
            "name":"isValid",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"bytes",
            "name":"challenge",
            "type":"bytes"
         },
         {
            "internalType":"bool",
            "name":"requireUserVerification",
            "type":"bool"
         },
         {
            "internalType":"bytes",
            "name":"authenticatorData",
            "type":"bytes"
         },
         {
            "internalType":"string",
            "name":"clientDataJSON",
            "type":"string"
         },
         {
            "internalType":"uint256",
            "name":"challengeIndex",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"typeIndex",
            "type":"uint256"
         },
         {
            "internalType":"bytes32",
            "name":"r",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"s",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"x",
            "type":"bytes32"
         },
         {
            "internalType":"bytes32",
            "name":"y",
            "type":"bytes32"
         }
      ],
      "name":"verifySoladySignature",
      "outputs":[
         {
            "internalType":"bool",
            "name":"isValid",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   }
] as const;